### ISSUE TITLE
Cygwin support broken

### ISSUE THREAD

**Issue by Danfun64** [kilobyte/termrec#3]
I'm trying to compile termrec under cygwin so I can use it with a cygwin compile brogue. However, I get an error regarding winsock2.h, which I shouldn't be getting in cygwin.

https://paste.debian.net/685541/

**Comment by kilobyte** [comment]
Fixed, sorry for the delay.

Note 1: the submodule is for native win32, for Cygwin you need to install their dev headers for zlib, bzip2 and lzma (otherwise compression support is not compiled in).  I've amended the documentation to mention this.

Note 2: I wonder what building for Cygwin **target** (rather than merely usiing Cygwin as a host for building Windows native) should do.  Currently it scrapes the win32 console using MSAA -- perhaps assuming an unixy pty would be better?  That'd break non-Cygwin guests (but those can be handled using Windows native) but make Cygwin-compiled guests work the unix way.
